source 'git@code.shihuo.cn:shihuoios/shihuomodulize/shmodulizespecs-bin.git'
source 'git@code.shihuo.cn:shihuoios/shihuomodulize/shmodulizespecs.git'
source 'git@code.shihuo.cn:shihuoios/shihuomodulize/shmodulizespecs_gray.git'
source 'git@code.shihuo.cn:shihuoios/shihuomodulize/shmodulizespecs_test.git'
source 'git@code.shihuo.cn:shihuoios/shihuospecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'ZFPlayer_Example' do
  pod 'ZFPlayer', :path => '../'

  target 'ZFPlayer_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer| 
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
            end
        end
    end 
