source 'git@code.shihuo.cn:shihuoios/shihuomodulize/shmodulizespecs-bin.git'
source 'git@code.shihuo.cn:shihuoios/shihuomodulize/shmodulizespecs.git'
source 'git@code.shihuo.cn:shihuoios/shihuomodulize/shmodulizespecs_gray.git'
source 'git@code.shihuo.cn:shihuoios/shihuomodulize/shmodulizespecs_test.git'
source 'git@code.shihuo.cn:shihuoios/shihuospecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.0'

target 'ZFPlayer_Example' do
  pod 'ZFPlayer', :path => '../'

  target 'ZFPlayer_Tests' do
    inherit! :search_paths

    
  end
end




post_install do |installer| 
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        end
    end
    dev_team = ''
    project = installer.aggregate_targets[0].user_project
    project.targets.each do |target|
        target.build_configurations.each do |config|
            if dev_team.empty? and !config.build_settings['DEVELOPMENT_TEAM'].nil?
                dev_team = config.build_settings['DEVELOPMENT_TEAM']
            end
        end
    end

    # Fix bundle targets' 'Signing Certificate' to 'Sign to Run Locally'
    installer.pods_project.targets.each do |target|
        if target.respond_to?(:product_type) and target.product_type == 'com.apple.product-type.bundle'
            target.build_configurations.each do |config|
                config.build_settings['DEVELOPMENT_TEAM'] = dev_team
            end
        end
    end
end 
